# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WvvDz7EdHDjm2T+78iMCC3QIScBLXMmlMPi2O/HP8+MT/+Xw2bskWhHfIANYn4zzf8YK0Q3pa3Z35BUe4TYmeGG2dui3SS+KhN6KAz1eTYI/mCxVxkFIBGOYObQjorpT6ML8x+V9EaCEtLkBZoMoFeX8jYN/2PzojjkWGL40cCXZlP8wWG4ZYy/A0ST5uY7zB621M1rFWwF2Hmj/oQnhxtkq68DcRekbQy2aURUG+hVv7O39I0ABh2WHQwpbU2Nz8CCeK9df8Rr3+U1NLOm2hdh1OzZo7Qip+EAIrdr9CGj2uMiZzOquHkw6VMP3znXWRYu96XADT32UMjrO2NGiISM6oytBV+Gyy/0zlkcRqNfQqUZs0u/8Al48Uc1GbP7inuPtchkFOFEl+slivu7UG4OQy2EMkt+Dxv0xdDufolPTcxdQXNE/62tF2iYgFYkU39pYarL1WOQJ9AFmzddIgn3+IjT5jLz2TTZnD4jvncrwViuAjbxH/Uz0Ceka2tW2Bqi0B095tNxfL+FcuNMLcoCX2540xuwvLqzvOlWN3Zx/eRIvS2JPQ6JzJgo2YCqbbozDHuaxszDQs0+u8QuOO4Taa5CWFWJxZZtYp/IuVl4RkP+Ao37hB9lRqK9Rbpc/qZqLkWn0DZVDsrJ7zl8lLiTjDKtwV87ehxRW1WDd5TU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
