travis:
  secure:
    BINSTAR_TOKEN: WvvDz7EdHDjm2T+78iMCC3QIScBLXMmlMPi2O/HP8+MT/+Xw2bskWhHfIANYn4zzf8YK0Q3pa3Z35BUe4TYmeGG2dui3SS+KhN6KAz1eTYI/mCxVxkFIBGOYObQjorpT6ML8x+V9EaCEtLkBZoMoFeX8jYN/2PzojjkWGL40cCXZlP8wWG4ZYy/A0ST5uY7zB621M1rFWwF2Hmj/oQnhxtkq68DcRekbQy2aURUG+hVv7O39I0ABh2WHQwpbU2Nz8CCeK9df8Rr3+U1NLOm2hdh1OzZo7Qip+EAIrdr9CGj2uMiZzOquHkw6VMP3znXWRYu96XADT32UMjrO2NGiISM6oytBV+Gyy/0zlkcRqNfQqUZs0u/8Al48Uc1GbP7inuPtchkFOFEl+slivu7UG4OQy2EMkt+Dxv0xdDufolPTcxdQXNE/62tF2iYgFYkU39pYarL1WOQJ9AFmzddIgn3+IjT5jLz2TTZnD4jvncrwViuAjbxH/Uz0Ceka2tW2Bqi0B095tNxfL+FcuNMLcoCX2540xuwvLqzvOlWN3Zx/eRIvS2JPQ6JzJgo2YCqbbozDHuaxszDQs0+u8QuOO4Taa5CWFWJxZZtYp/IuVl4RkP+Ao37hB9lRqK9Rbpc/qZqLkWn0DZVDsrJ7zl8lLiTjDKtwV87ehxRW1WDd5TU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
