travis:
  secure:
    BINSTAR_TOKEN: uwJCDNJLYi1IeH63wf3hkQC1pMy8iaJEwqWD5fKb2Bo5ugrlRxNPMX9lwH07AROVLQXuwH+ahBGth86Y/qUnVMiXwCfSO4aNRE9UIe9+SFVnBeQrVIOpM4Tb0v+ttz9jV8vqsR4DQ+XydPtF2I/yKnuDBFYCVWomYgjQeswCxE4f0KGDz+RTvjS7l8PxLAEFA5asaBULJfH9Q44Xak5lzyYkVgRjS14fL3eLA3eKNE5PzAwTfaq/6lDAYZOdzUFQ4DO81X0foUasjvqcIMuoWJUSV5jTa9qQ6F5M59VTjXby5IztMjb/TnBizw/Z6eKLoRiBYY07wesMgcbYiLEMsesHQvrjoBwpOykBsyGt0WzaOroeIlRKSS9gaZUiwJCstNvoamF+cRPK2KEO900+B2rP//11R7byVf/kOFhu6HRa9s7307hqOnn84tIwNHWeSC/XbLd9BFp9GkPn0GKu+8Nb2sDXmsMfjEnhucpsWnMAMPtdPc1qTOPPVPuogJ0icYwTQoPEbXJSo+Dc69stnNbyZpiZbN+anovR00FK9/F78HfGShUkkkSdw7oRrYIyRtxQgaIIU779dXpgiIUHn4dc4vYqlHjKh0qFdtLrzgIJfNr5bYzG40GDT9Z58YYvhbkIuF8+T9iyL+C3DcSL5Lc0KefyCfKRbdYv7EjzDKE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
